# Generated by Django 2.1.3 on 2018-11-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0002_auto_20181110_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='completev',
            name='picture',
            field=models.ImageField(null=True, upload_to='complete_view'),
        ),
        migrations.AddField(
            model_name='detailv',
            name='picture',
            field=models.ImageField(null=True, upload_to='detail_view'),
        ),
    ]
