# Generated by Django 2.1.3 on 2018-11-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0003_auto_20181110_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completev',
            name='link',
            field=models.CharField(max_length=550),
        ),
    ]
