# Generated by Django 2.1.3 on 2018-11-25 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0008_auto_20181111_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailv',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picsna/static/images/detail_view'),
            preserve_default=False,
        ),
    ]
