# Generated by Django 2.1.3 on 2018-11-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0013_auto_20181127_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailv',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
