# Generated by Django 2.1.3 on 2018-12-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0016_remove_detailv_completev'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailv',
            name='completev',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='picsna.CompleteV'),
        ),
    ]
