# Generated by Django 2.1.3 on 2018-11-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0006_auto_20181110_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completev',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/images/complete_view'),
        ),
        migrations.AlterField(
            model_name='detailv',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/images/detail_view'),
        ),
    ]
