# Generated by Django 2.1.3 on 2018-11-27 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0012_auto_20181127_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailv',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
