# Generated by Django 2.1.3 on 2018-12-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picsna', '0015_auto_20181127_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailv',
            name='completev',
        ),
    ]
